// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SMSProtocol.proto

package org.aaron.sms.entities.protobuf;

public final class SMSProtocol {
  private SMSProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientToServerMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .sms.entities.protobuf.ClientToServerMessage.ClientToServerMessageType messageType = 1;
    boolean hasMessageType();
    org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.ClientToServerMessageType getMessageType();
    
    // required string topicName = 2;
    boolean hasTopicName();
    String getTopicName();
    
    // optional bytes messagePayload = 3;
    boolean hasMessagePayload();
    com.google.protobuf.ByteString getMessagePayload();
  }
  public static final class ClientToServerMessage extends
      com.google.protobuf.GeneratedMessage
      implements ClientToServerMessageOrBuilder {
    // Use ClientToServerMessage.newBuilder() to construct.
    private ClientToServerMessage(Builder builder) {
      super(builder);
    }
    private ClientToServerMessage(boolean noInit) {}
    
    private static final ClientToServerMessage defaultInstance;
    public static ClientToServerMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClientToServerMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.aaron.sms.entities.protobuf.SMSProtocol.internal_static_sms_entities_protobuf_ClientToServerMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.aaron.sms.entities.protobuf.SMSProtocol.internal_static_sms_entities_protobuf_ClientToServerMessage_fieldAccessorTable;
    }
    
    public enum ClientToServerMessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      CLIENT_SUBSCRIBE_TO_TOPIC(0, 0),
      CLIENT_UNSUBSCRIBE_FROM_TOPIC(1, 1),
      CLIENT_SEND_MESSAGE_TO_TOPIC(2, 2),
      ;
      
      public static final int CLIENT_SUBSCRIBE_TO_TOPIC_VALUE = 0;
      public static final int CLIENT_UNSUBSCRIBE_FROM_TOPIC_VALUE = 1;
      public static final int CLIENT_SEND_MESSAGE_TO_TOPIC_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static ClientToServerMessageType valueOf(int value) {
        switch (value) {
          case 0: return CLIENT_SUBSCRIBE_TO_TOPIC;
          case 1: return CLIENT_UNSUBSCRIBE_FROM_TOPIC;
          case 2: return CLIENT_SEND_MESSAGE_TO_TOPIC;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<ClientToServerMessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ClientToServerMessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ClientToServerMessageType>() {
              public ClientToServerMessageType findValueByNumber(int number) {
                return ClientToServerMessageType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final ClientToServerMessageType[] VALUES = {
        CLIENT_SUBSCRIBE_TO_TOPIC, CLIENT_UNSUBSCRIBE_FROM_TOPIC, CLIENT_SEND_MESSAGE_TO_TOPIC, 
      };
      
      public static ClientToServerMessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private ClientToServerMessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:sms.entities.protobuf.ClientToServerMessage.ClientToServerMessageType)
    }
    
    private int bitField0_;
    // required .sms.entities.protobuf.ClientToServerMessage.ClientToServerMessageType messageType = 1;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.ClientToServerMessageType messageType_;
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.ClientToServerMessageType getMessageType() {
      return messageType_;
    }
    
    // required string topicName = 2;
    public static final int TOPICNAME_FIELD_NUMBER = 2;
    private java.lang.Object topicName_;
    public boolean hasTopicName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTopicName() {
      java.lang.Object ref = topicName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          topicName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTopicNameBytes() {
      java.lang.Object ref = topicName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        topicName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes messagePayload = 3;
    public static final int MESSAGEPAYLOAD_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString messagePayload_;
    public boolean hasMessagePayload() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getMessagePayload() {
      return messagePayload_;
    }
    
    private void initFields() {
      messageType_ = org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.ClientToServerMessageType.CLIENT_SUBSCRIBE_TO_TOPIC;
      topicName_ = "";
      messagePayload_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTopicName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTopicNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, messagePayload_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTopicNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, messagePayload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.aaron.sms.entities.protobuf.SMSProtocol.internal_static_sms_entities_protobuf_ClientToServerMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.aaron.sms.entities.protobuf.SMSProtocol.internal_static_sms_entities_protobuf_ClientToServerMessage_fieldAccessorTable;
      }
      
      // Construct using org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        messageType_ = org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.ClientToServerMessageType.CLIENT_SUBSCRIBE_TO_TOPIC;
        bitField0_ = (bitField0_ & ~0x00000001);
        topicName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        messagePayload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.getDescriptor();
      }
      
      public org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage getDefaultInstanceForType() {
        return org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.getDefaultInstance();
      }
      
      public org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage build() {
        org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage buildPartial() {
        org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage result = new org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.topicName_ = topicName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.messagePayload_ = messagePayload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage) {
          return mergeFrom((org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage other) {
        if (other == org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasTopicName()) {
          setTopicName(other.getTopicName());
        }
        if (other.hasMessagePayload()) {
          setMessagePayload(other.getMessagePayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMessageType()) {
          
          return false;
        }
        if (!hasTopicName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.ClientToServerMessageType value = org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.ClientToServerMessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                messageType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              topicName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              messagePayload_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .sms.entities.protobuf.ClientToServerMessage.ClientToServerMessageType messageType = 1;
      private org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.ClientToServerMessageType messageType_ = org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.ClientToServerMessageType.CLIENT_SUBSCRIBE_TO_TOPIC;
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.ClientToServerMessageType getMessageType() {
        return messageType_;
      }
      public Builder setMessageType(org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.ClientToServerMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        messageType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.ClientToServerMessageType.CLIENT_SUBSCRIBE_TO_TOPIC;
        onChanged();
        return this;
      }
      
      // required string topicName = 2;
      private java.lang.Object topicName_ = "";
      public boolean hasTopicName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTopicName() {
        java.lang.Object ref = topicName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          topicName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTopicName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        topicName_ = value;
        onChanged();
        return this;
      }
      public Builder clearTopicName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        topicName_ = getDefaultInstance().getTopicName();
        onChanged();
        return this;
      }
      void setTopicName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        topicName_ = value;
        onChanged();
      }
      
      // optional bytes messagePayload = 3;
      private com.google.protobuf.ByteString messagePayload_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasMessagePayload() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getMessagePayload() {
        return messagePayload_;
      }
      public Builder setMessagePayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        messagePayload_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessagePayload() {
        bitField0_ = (bitField0_ & ~0x00000004);
        messagePayload_ = getDefaultInstance().getMessagePayload();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:sms.entities.protobuf.ClientToServerMessage)
    }
    
    static {
      defaultInstance = new ClientToServerMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sms.entities.protobuf.ClientToServerMessage)
  }
  
  public interface ServerToClientMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .sms.entities.protobuf.ServerToClientMessage.ServerToClientMessageType messageType = 1;
    boolean hasMessageType();
    org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.ServerToClientMessageType getMessageType();
    
    // required string topicName = 2;
    boolean hasTopicName();
    String getTopicName();
    
    // optional bytes messagePayload = 3;
    boolean hasMessagePayload();
    com.google.protobuf.ByteString getMessagePayload();
  }
  public static final class ServerToClientMessage extends
      com.google.protobuf.GeneratedMessage
      implements ServerToClientMessageOrBuilder {
    // Use ServerToClientMessage.newBuilder() to construct.
    private ServerToClientMessage(Builder builder) {
      super(builder);
    }
    private ServerToClientMessage(boolean noInit) {}
    
    private static final ServerToClientMessage defaultInstance;
    public static ServerToClientMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ServerToClientMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.aaron.sms.entities.protobuf.SMSProtocol.internal_static_sms_entities_protobuf_ServerToClientMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.aaron.sms.entities.protobuf.SMSProtocol.internal_static_sms_entities_protobuf_ServerToClientMessage_fieldAccessorTable;
    }
    
    public enum ServerToClientMessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      SERVER_TOPIC_MESSAGE_PUBLISH(0, 0),
      ;
      
      public static final int SERVER_TOPIC_MESSAGE_PUBLISH_VALUE = 0;
      
      
      public final int getNumber() { return value; }
      
      public static ServerToClientMessageType valueOf(int value) {
        switch (value) {
          case 0: return SERVER_TOPIC_MESSAGE_PUBLISH;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<ServerToClientMessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ServerToClientMessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ServerToClientMessageType>() {
              public ServerToClientMessageType findValueByNumber(int number) {
                return ServerToClientMessageType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final ServerToClientMessageType[] VALUES = {
        SERVER_TOPIC_MESSAGE_PUBLISH, 
      };
      
      public static ServerToClientMessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private ServerToClientMessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:sms.entities.protobuf.ServerToClientMessage.ServerToClientMessageType)
    }
    
    private int bitField0_;
    // required .sms.entities.protobuf.ServerToClientMessage.ServerToClientMessageType messageType = 1;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.ServerToClientMessageType messageType_;
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.ServerToClientMessageType getMessageType() {
      return messageType_;
    }
    
    // required string topicName = 2;
    public static final int TOPICNAME_FIELD_NUMBER = 2;
    private java.lang.Object topicName_;
    public boolean hasTopicName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTopicName() {
      java.lang.Object ref = topicName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          topicName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTopicNameBytes() {
      java.lang.Object ref = topicName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        topicName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes messagePayload = 3;
    public static final int MESSAGEPAYLOAD_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString messagePayload_;
    public boolean hasMessagePayload() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getMessagePayload() {
      return messagePayload_;
    }
    
    private void initFields() {
      messageType_ = org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.ServerToClientMessageType.SERVER_TOPIC_MESSAGE_PUBLISH;
      topicName_ = "";
      messagePayload_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTopicName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTopicNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, messagePayload_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTopicNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, messagePayload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.aaron.sms.entities.protobuf.SMSProtocol.internal_static_sms_entities_protobuf_ServerToClientMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.aaron.sms.entities.protobuf.SMSProtocol.internal_static_sms_entities_protobuf_ServerToClientMessage_fieldAccessorTable;
      }
      
      // Construct using org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        messageType_ = org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.ServerToClientMessageType.SERVER_TOPIC_MESSAGE_PUBLISH;
        bitField0_ = (bitField0_ & ~0x00000001);
        topicName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        messagePayload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.getDescriptor();
      }
      
      public org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage getDefaultInstanceForType() {
        return org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.getDefaultInstance();
      }
      
      public org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage build() {
        org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage buildPartial() {
        org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage result = new org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.topicName_ = topicName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.messagePayload_ = messagePayload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage) {
          return mergeFrom((org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage other) {
        if (other == org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasTopicName()) {
          setTopicName(other.getTopicName());
        }
        if (other.hasMessagePayload()) {
          setMessagePayload(other.getMessagePayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMessageType()) {
          
          return false;
        }
        if (!hasTopicName()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.ServerToClientMessageType value = org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.ServerToClientMessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                messageType_ = value;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              topicName_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              messagePayload_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .sms.entities.protobuf.ServerToClientMessage.ServerToClientMessageType messageType = 1;
      private org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.ServerToClientMessageType messageType_ = org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.ServerToClientMessageType.SERVER_TOPIC_MESSAGE_PUBLISH;
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.ServerToClientMessageType getMessageType() {
        return messageType_;
      }
      public Builder setMessageType(org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.ServerToClientMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        messageType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.ServerToClientMessageType.SERVER_TOPIC_MESSAGE_PUBLISH;
        onChanged();
        return this;
      }
      
      // required string topicName = 2;
      private java.lang.Object topicName_ = "";
      public boolean hasTopicName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTopicName() {
        java.lang.Object ref = topicName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          topicName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTopicName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        topicName_ = value;
        onChanged();
        return this;
      }
      public Builder clearTopicName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        topicName_ = getDefaultInstance().getTopicName();
        onChanged();
        return this;
      }
      void setTopicName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        topicName_ = value;
        onChanged();
      }
      
      // optional bytes messagePayload = 3;
      private com.google.protobuf.ByteString messagePayload_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasMessagePayload() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getMessagePayload() {
        return messagePayload_;
      }
      public Builder setMessagePayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        messagePayload_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessagePayload() {
        bitField0_ = (bitField0_ & ~0x00000004);
        messagePayload_ = getDefaultInstance().getMessagePayload();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:sms.entities.protobuf.ServerToClientMessage)
    }
    
    static {
      defaultInstance = new ServerToClientMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:sms.entities.protobuf.ServerToClientMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sms_entities_protobuf_ClientToServerMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sms_entities_protobuf_ClientToServerMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_sms_entities_protobuf_ServerToClientMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_sms_entities_protobuf_ServerToClientMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021SMSProtocol.proto\022\025sms.entities.protob" +
      "uf\"\240\002\n\025ClientToServerMessage\022[\n\013messageT" +
      "ype\030\001 \002(\0162F.sms.entities.protobuf.Client" +
      "ToServerMessage.ClientToServerMessageTyp" +
      "e\022\021\n\ttopicName\030\002 \002(\t\022\026\n\016messagePayload\030\003" +
      " \001(\014\"\177\n\031ClientToServerMessageType\022\035\n\031CLI" +
      "ENT_SUBSCRIBE_TO_TOPIC\020\000\022!\n\035CLIENT_UNSUB" +
      "SCRIBE_FROM_TOPIC\020\001\022 \n\034CLIENT_SEND_MESSA" +
      "GE_TO_TOPIC\020\002\"\336\001\n\025ServerToClientMessage\022" +
      "[\n\013messageType\030\001 \002(\0162F.sms.entities.prot",
      "obuf.ServerToClientMessage.ServerToClien" +
      "tMessageType\022\021\n\ttopicName\030\002 \002(\t\022\026\n\016messa" +
      "gePayload\030\003 \001(\014\"=\n\031ServerToClientMessage" +
      "Type\022 \n\034SERVER_TOPIC_MESSAGE_PUBLISH\020\000B." +
      "\n\037org.aaron.sms.entities.protobufB\013SMSPr" +
      "otocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_sms_entities_protobuf_ClientToServerMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_sms_entities_protobuf_ClientToServerMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sms_entities_protobuf_ClientToServerMessage_descriptor,
              new java.lang.String[] { "MessageType", "TopicName", "MessagePayload", },
              org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.class,
              org.aaron.sms.entities.protobuf.SMSProtocol.ClientToServerMessage.Builder.class);
          internal_static_sms_entities_protobuf_ServerToClientMessage_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_sms_entities_protobuf_ServerToClientMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_sms_entities_protobuf_ServerToClientMessage_descriptor,
              new java.lang.String[] { "MessageType", "TopicName", "MessagePayload", },
              org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.class,
              org.aaron.sms.entities.protobuf.SMSProtocol.ServerToClientMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
